[workspace]
members = [
    "arch",
    "basic",
    "config",
    "corelib",
    "domain_main",
    "gproxy",
    "interface",
    "ksync",
    "malloc",
    "rref",
    "storage",
    "task_meta",
]


resolver = "2"