[package]
name = "loader"
version = "0.1.0"
edition = "2021"

[dependencies]
corelib = { path = "../corelib" }
rref = { path = "../rref" }
storage = { path = "../storage" }

xmas-elf = "0.9"
bitflags = "2.6.0"
memory_addr = { git ="https://github.com/os-module/memory_addr" }
log = "0"